[project]
name = "weather_app_vkyei"
version = "0.1.2"
description = "Homework done"
readme = "README.md"
authors = [
    { name = "AIMinister", email = "vkyei47@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "python-dotenv>=1.2.2",
    "requests>=2.33.1"
]

[project.scripts]
weather = "weather_app.cli:main"

[build-system]
requires = ["uv_build>=0.11.1,<0.12.0"]
build-backend = "uv_build"
